#pragma config(Sensor, in1,    pot,            sensorPotentiometer)
#pragma config(Motor,  port1,           LBDrive,       tmotorVex393, openLoop)
#pragma config(Motor,  port2,           LFDrive,       tmotorVex393, openLoop)
#pragma config(Motor,  port3,           LTArm,         tmotorVex269, openLoop, reversed)
#pragma config(Motor,  port4,           LBArm,         tmotorVex269, openLoop, reversed)
#pragma config(Motor,  port5,           ScoopLeft,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           ScoopRight,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           RBArm,         tmotorVex269, openLoop)
#pragma config(Motor,  port8,           RTArm,         tmotorVex269, openLoop)
#pragma config(Motor,  port9,           RFDrive,       tmotorVex393, openLoop)
#pragma config(Motor,  port10,          RBDrive,       tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
  while(true)
  {
    motor[LFDrive] = vexRT[Ch3];
    motor[LBDrive] = vexRT[Ch3];
    motor[RFDrive] = vexRT[Ch2];
    motor[RBDrive] = vexRT[Ch2];

    if(vexRT[Btn5U] == 1)
    {
      motor[ScoopLeft] = 127;
      motor[ScoopRight] = 127;
    }
    else if(vexRT[Btn5D] == 1)
    {
      motor[ScoopLeft] = 127;
      motor[ScoopRight] = 127;
    }
    else if(vexRT[Btn5U] != 1 && vexRT[Btn5D] != 1)
    {
      motor[ScoopLeft] = 0;
      motor[ScoopRight] = 0;
    }


    if(vexRT[Btn6U] == 1)
    {
      motor[LTArm] = 127;
      motor[LBArm] = 127;
      motor[RTArm] = 127;
      motor[RBArm] = 127;
    }
    else if(vexRT[Btn6D] == 1)
    {
      motor[LTArm] = -127;
      motor[LBArm] = -127;
      motor[RTArm] = -127;
      motor[RBArm] = -127;
    }
    else if(vexRT[Btn6U] != 1 && vexRT[Btn6D] != 1)
    {
      motor[LTArm] = 0;
      motor[LBArm] = 0;
      motor[RTArm] = 0;
      motor[RBArm] = 0;
    }
  }
}
