#pragma config(Motor,  port1,            ,             tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port2,            ,             tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port3,            ,             tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port4,            ,             tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port5,            ,             tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port6,            ,             tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port7,            ,             tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port8,            ,             tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port9,            ,             tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port10,           ,             tmotorVex393HighSpeed, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
setAllMotorHiSpeed();
}
